### ISSUE TITLE
GUI Error (Overdraw?) on Windows 10

### ISSUE THREAD

**Issue by JazzaHat** [hneemann/Digital#227]
Hi,
I've had this issue for a while now: the GUI seems to overdraw, I believe the right word is. Sometimes this doesn't show up for minutes, sometimes its immediate. Dragging the window to a different screen "fixes" the GUI until it errors again. The program itself seems to continue working and saving just fine.
![image](https://user-images.githubusercontent.com/17369726/50880160-67843900-1418-11e9-9ab4-09a58af01499.png)
I also have this issue in Logisim.
I have tried multiple Digital versions, uninstalling and reinstalling of: Java, Graphics drivers.
I have also recently upgraded my GPU and have a fresh install of windows.
I am not sure if there are any alternative settings I can use, but I have tried looking in the settings menu and I'm unable to find anything that seems to help.
This might not be a problem with Digital, however it (and Logisim) are the only two programs that reproduce this issue for me. Any ideas?

EDIT: After googling some different terms it appears that the problem is with Java; the following workaround appears to work: https://stackoverflow.com/questions/22737535/swing-rendering-appears-broken-in-jdk-1-8-correct-in-jdk-1-7

Setting environmental variable in windows:  J2D_D3D = false

**Comment by hneemann** [comment]
I have added a new EXE wrapper which turns of D3D. Please try the latest [pre release](https://infdigital.dhbw-mosbach.de/).
There is a new EXE wrapper called "Digital_noD3D.exe".
Please remove your J2D_D3D = false environment variable and try the new Wrapper.
If every thing works like expected, using the Digital.exe wrapper should still show the problem and using the Digital_noD3D.exe wrapper should fix it.

**Comment by JazzaHat** [comment]
Yup, Digital.exe does show the problem and Digital_noD3D.exe didn't appear to show the problem :) 
Thank you very much!

**Comment by JazzaHat** [comment]
Actually it still appears to be a thing. I was using it for the past few hours fine, then I opened up a second window. I am definitely using the noD3D version.

![image](https://user-images.githubusercontent.com/17369726/51030506-9941ff00-15d4-11e9-84fd-f43458173e68.png)

I guess the current work around is to only have one instance open at once?

If there's any other debug information you want let me know.

Thanks, Jazza

**Comment by hneemann** [comment]
To be honest: I have no idea what is going on on your machine!
Did you turn on display scaling? Maybe it is this [bug](https://bugs.openjdk.java.net/browse/JDK-8187367).

**Comment by inacioalves** [comment]
<img width="379" alt="Digital_GUI_Error" src="https://user-images.githubusercontent.com/313711/75091196-55e0f080-5549-11ea-9bc5-b99e7a98a358.png">
Hi guys, I just start to trying the Digital and I found this problem. The logic ports icons don't have correct appearance.
There is any way to solve this?

Thanks in advance.

**Comment by hneemann** [comment]
I the settings you can select IEEE 91-1984 shapes.

**Comment by Roger13h** [comment]
IM hitting this issue ,, after 5 min or so of use ..  display elements seem to be off on the display ,

**Comment by THplusplus** [comment]
Unfortunately, I'm still experiencing graphical glitches in the UI:

![Image](https://github.com/user-attachments/assets/8eae10ae-bd38-4f8c-8edf-ab97d92114ba)

This is easily reproducible:

1. start Digital.exe (or Digital_noD3D.exe, problem occurs with either)
2. add a simple "RAM, Chip Select" component
3. right click it to open its properties
4. Select any value from the "Data Bits" drop down
5. No the UI is glitched. Hovering over different UI elements with the mouse will immediately cause graphical glitches as shown in the screenshot

Environment:
* Windows 11 Pro 24H2 (26100.3476)
* Java Version 8, Update 441

PS: I was just about to send this post like this, then I got it working by starting it with

`java -Dsun.java2d.d3d=false -jar Digital.jar` <= THIS WORKS for me

I had tried

`java -jar Digital.jar -Dsun.java2d.d3d=false` before, which didn't work. I'm no Java guy, I don't know that the order of the command line arguments matters here.

Can't you make sun.java2d.d3d=false the default internally? I was SO close to giving up on what I'm sure is actually a great tool, I really only got saved by luck here. I bet this has driven way A LOT of first time users.
